### ISSUE TITLE
Add option to search for direct subclasses with `under`

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/valve.py#11]
This corresponds to the `direct-subclass-of` rule used in ROBOT validate, although I'm wondering if we should make it a bit more flexible?

I have two ideas:
1. `under(table.column, "parent", direct=true)` - only allows direct subclasses (does not include the parent term)
2. `under(table.column, "parent", level=X)` - only allows terms up to X levels down, e.g. if you say `level=1` it only allows the direct subclasses

I'm leaning towards the first option because I can't think of a use case for anything other than `level=1` but I could be wrong.

**Comment by jamesaoverton** [comment]
I like `direct=true`.
