### ISSUE TITLE
Handle non-string values in `validate_datatype`

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/valve.py#45]
Some tools that generate TSV and CSV drop empty cells at the end of a row. Then Python will read these as `None`. We can't match a regex to `None`. I ran into the problem here:

https://github.com/ontodev/valve.py/blob/main/valve/valve.py#L819

My quick solution was to wrap in `str`, so `if not datatype["match"].match(str(value)):`, but I'm not sure if that's the right solution or the right place for it.

**Comment by beckyjackson** [comment]
Hmm, I already set to an empty string if the value doesn't exist: https://github.com/ontodev/valve.py/blob/main/valve/valve.py#L123

But maybe it's a "then" value? I'll add another check here: https://github.com/ontodev/valve.py/blob/main/valve/valve.py#L155

**Comment by jamesaoverton** [comment]
The specific problem I had was that my `datatype.replace` cells were missing and thus `None`. I ended up messing with Google Sheets until those cells were blank instead. So now I'm not sure what we want to do. The error was not helpful:

```
...
  File "/Users/james/Repositories/github/ontodev/valve.py/valve/valve.py", line 820, in validate_datatype                                                                                     
    if not datatype["match"].match(value):                                                                                                                                                    
TypeError: expected string or bytes-like object 
```

**Comment by beckyjackson** [comment]
Oh I see - OK, I'll look into that.

**Comment by beckyjackson** [comment]
Can you send me your test data? I'm still a little confused because this should be prevented by `if datatype.get("replace")`
