### ISSUE TITLE
Extend `tree` function

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/valve.py#7]
I'm thinking that the `tree` function needs to be able to do more than it currently does. My use-case is ONTIE, where the tables are interlinked. For example, the `disease` table uses parent values from `external`, but the `external` table also uses parent values form `disease`. We can't build one of these trees first without running into errors.

Additionally, sometimes the parent column contains a split character (usually `|`) so we need a way to handle this.

I suggest that `tree` accepts between zero and three arguments:
* **No args**:`table.Label = tree()`
    * builds a tree of children only (the parent values are an empty set) where the keys are the contents of `table.Label`
* **One arg**:`table.Parent = tree(table.Label)`
    * builds a tree `table.Parent` where allowed values come from `table.Label` (current functionality)
* **Two args A**:`table.Parent = tree(table.Label, "char")`
    * builds a tree `table.Parent` where allowed values come from `table.Label` and `table.Parent` can be split on "char"
* **Two args B**:`table2.Parent = tree(table2.Label, table.Parent)`
    * builds a tree `table2.Parent` that starts with previously-built tree `table.Parent` where more allowed values come from `table2.Label`
* **Three args**:`table2.Parent = tree(table2.column2, "char", table.column)`
    * builds a tree `table2.Parent` that starts with previously-built tree `table.Parent` where more allowed values come from `table2.Label` and `table2.Parent` can be split on "char"

Here's how it looks with ONTIE:

table | column | type | note
-- | -- | -- | --
index | Label | tree() | Build a tree with no parents to use ONTIE terms as external parents   (these parents will be updated as we extend the tree)
external | Parent | tree(external.Label, "\|", index.Label) | Extend the index tree with external terms
complex | Parent | tree(complex.Label, "\|", external.Parent) | Extend the external tree with complex terms
disease | Parent | tree(disease.Label, "\|", external.Parent) | Extend the external tree with disease terms
taxon | Parent | tree(taxon.Label, "\|", external.Parent) | Extend the external tree with taxon terms

First, a "tree" with no parents is built from the `index.Label` column. This allows all ONTIE terms to be used when extending this tree. Then, `external.Parent` is built by extending the `index.Label` tree. This `external.Parent` tree is then used to extend the complex, disease, and taxon trees.

And the corresponding code for handling the args:
```python
if len(args) == 0:
    # Build a tree without parents
    tree = {}
    rows = config["table_details"][tree_table]["rows"]
    for row in rows:
        tree[row[tree_column]] = set()
    return tree, errors

tree_table_name = args[0]["table"]
if tree_table_name != tree_table:
    # ... (error)
    return None, errors
else:
    add_tree_name = None
    split_char = None
    # TODO - validate
    if len(args) == 2:
        # If there are two args, the second is either a split or a tree to extend
        if "table" in args[1]:
            add_tree = args[1]
            add_tree_name = f'{add_tree["table"]}.{add_tree["column"]}'
        else:
            split_char = args[1]
    if len(args) == 3:
        # If there are three args, the second is split and third is tree to extend
        split_char = args[1]
        add_tree = args[2]
        add_tree_name = f'{add_tree["table"]}.{add_tree["column"]}'
    child_column = args[0]["column"]
    return build_tree(
        config,
        fn_loc,
        tree_table,
        tree_column,
        child_column,
        add_tree_name=add_tree_name,
        split_char=split_char,
    )
```

**Comment by jamesaoverton** [comment]
We will need to be able to split on a character, but we discussed how to shuffle things around a bit in ONTIE, and I hope that will eliminate the need for inter-dependent trees.
